cultuurnet/udb3-angular-app

- app/index.html
- Load the angulare-filters bower dependency, this bower dependency is installed in the  `udb3-angular` repository.
> III-2387 load new bower dependency

- app/index.html
This is done automatically by running bower install in combination with https://github.com/cultuurnet/udb3-angular/pull/513
> III-2939 Update list of bower component script tags

- config.json.dist
- added feature toggle for loading places async
tickets: 
[https://jira.uitdatabank.be/browse/III-3030](https://jira.uitdatabank.be/browse/III-3030)
[https://jira.uitdatabank.be/browse/III-3041](https://jira.uitdatabank.be/browse/III-3041)
> III-3030 - added feature toggle setting in config

- config.json.dist
- added missing cultuurkuur info in `config.json.dist`
Ticket: [https://jira.uitdatabank.be/browse/III-2991](https://jira.uitdatabank.be/browse/III-2991)
> III-2991 - add missing cultuurkuur config

- config.json.dist
Removed:
- asyncPlaceSuggestionsFeatureToggle from config
>  remove feature toggle

- app/scripts/controllers/main.js
- app/views/main.html
- config.json.dist
- hide register if hideRegistered in config is set to true
Ticket: [https://jira.uitdatabank.be/browse/III-3215](https://jira.uitdatabank.be/browse/III-3215)
> III-3215 - hide register if hideRegistered in config is set to true

- config.json.dist
- change publicationRulesLink
Ticket: [https://jira.uitdatabank.be/browse/III-3187](https://jira.uitdatabank.be/browse/III-3187)
> III-3187 - change publicationRulesLink

- app/scripts/controllers/main.js
- added missing dependency injection
Ticket: [https://jira.uitdatabank.be/browse/III-3215](https://jira.uitdatabank.be/browse/III-3215)
> III-3215 bugfix - added missing dependency injection

- config.json.dist
- feature toggle to show public service announcements
Ticket: [https://jira.uitdatabank.be/browse/III-3257](https://jira.uitdatabank.be/browse/III-3257)
> III-3257 - feature toggle to show public service announcements

- .travis.yml
- app/scripts/translations/dutch-translations.constant.js
- app/scripts/translations/french-translations.constant.js
- app/views/main.html
- added link to form for online activities on homepage
- changed node version of travis.yml so it corresponds with the node version used in deploy
Ticket: [https://jira.uitdatabank.be/browse/III-3267](https://jira.uitdatabank.be/browse/III-3267)
> III-3267 - added link to form for online activities on homepage

- config.json.dist
- removed disableVariations feature toggle from example config
Ticket: [https://jira.uitdatabank.be/browse/III-3170](https://jira.uitdatabank.be/browse/III-3170)
> III-3170 - remove disableVariations feature toggle from example config

- app/scripts/translations/dutch-translations.constant.js
- app/scripts/translations/french-translations.constant.js
- app/views/main.html
- Deleted corona message under login button
Ticket: [https://jira.uitdatabank.be/browse/III-3327](https://jira.uitdatabank.be/browse/III-3327)
> III-3327 - Delete corona message under login button

- config.json.dist
- deleted beta text from config
Ticket: [https://jira.uitdatabank.be/browse/III-3239](https://jira.uitdatabank.be/browse/III-3239)
> III-3239 - deleted beta text from config

- app/scripts/app.js
- app/scripts/controllers/split-view.js
- app/styles/side-bar.less
- app/views/split-view.html
- postMessage to communicate the route of the app to the Vue app
- hide sidebar when the application is running from within an iFrame
linked to https://jira.uitdatabank.be/browse/III-3338
> Preparations for Angular in Vue setup

- app/scripts/app.js
- remove JWT of query string before sending it to the parent window
> Remove JWT from message to parent frame

- app/views/footer.html
- target to a tag
Linked to https://jira.uitdatabank.be/browse/III-3443
> Add target to publiq link

- app/scripts/app.js
- Fixed URL for organizer edit route
---
Ticket: https://jira.uitdatabank.be/browse/III-3444
> III-3444 Fix registered route url for organizer edit page

- app/scripts/app.js
- Fixed pages loading twice because AngularJS starts rendering them, and then the Vue parent window re-renders the iframe
> Fix double loading of certain pages inside iframe

- app/views/newsletter.html
- Removed 'monthly' from newsletter copy
> Newsletter is not monthly at the moment

- app/styles/bootstrap-overrides.less
- Remove override for chevron icons
---
Ticket:https://jira.uitdatabank.be/browse/III-3827
> III-3827 Remove override for chevron icons

- config.json.dist
- Fix uitpas url in config example
> Fix uitpas url in config example

- bower.json
- Pin angular-translate to version 2.15.1
> Pin angular-translate to version 2.15.1

- app/scripts/app.js
- edit redirect path to movie ui
[Related PR](https://github.com/cultuurnet/udb3-angular/pull/697)
Ticket: https://jira.uitdatabank.be/browse/III-3549
> III-3549 - Add redirect to movie ui

- app/styles/app.less
-  Rounded corners
---
Ticket: https://jira.uitdatabank.be/browse/III-4922
> III-4922 - Add styling to round components in the angular app

- app/styles/app.less
- Refinements rounded corners
---
Ticket: https://jira.uitdatabank.be/browse/III-4922
> III-4922 - Refinements rounded corners

- app/styles/app.less
> III-5044 - Fix datepicker css

- app/styles/app.less
- Add margin between include and exclude buttons
Ticket: https://jira.uitdatabank.be/browse/III-5040
After change:
> III-5040 - Add margin between include and exclude buttons

- app/styles/app.less
- Fix pagination layout
Ticket: https://jira.uitdatabank.be/browse/III-5036
After change:
> III-5036 - Fix pagination layout

- app/styles/app.less
Fix and or spacing
https://jira.uitdatabank.be/browse/III-5040
> III-5040 - Fix and or spacing

- app/styles/app.less
- Add more contrast to secondary buttons
Ticket: https://jira.uitdatabank.be/browse/III-5039
> III-5039 - Add more contrast to secondary buttons

- app/styles/app.less
- Remove box-shadow on dropdown toggles
---
https://jira.uitdatabank.be/browse/III-5090
> Remove box-shadow on dropdown toggles

- app/styles/main.less
- [Style panels according to new design](https://github.com/cultuurnet/udb3-angular-app/commit/9c3e9929a22c0d4e62a70d119e8f37116ac643ea)
- [Change color of warning-icon](https://github.com/cultuurnet/udb3-angular-app/pull/208/commits/e591e4139db2bfce4833435d28893a370c18e2bd)
- [Make btn color consistent with alert-info alert](https://github.com/cultuurnet/udb3-angular-app/pull/208/commits/c108a1d449be9659ffaa66030777ff99a6183f4f)
Tickets: 
- https://jira.publiq.be/browse/III-5851
- https://jira.publiq.be/browse/III-5929
- https://jira.publiq.be/browse/III-5933
> III-5851 - Style panels according to new design

- app/scripts/services/migration-redirect.js
- Do not send users to /migrate anymore (since the behavior has been added to /edit)
---
Keeping the PR in draft until the beta toggle is phased out (since this change doesn't account for it)
---
Ticket: https://jira.uitdatabank.be/browse/III-5590
> Do not send users to /migrate anymore 

- app/styles/main.less
- [Reservation button on /preview page](https://github.com/cultuurnet/udb3-angular-app/commit/716e804befa2fe8874d161f9e1008c312cb2e947)
- [styling for organizer detail preview page](https://github.com/cultuurnet/udb3-angular-app/commit/e17b9f91d07e1aaa04dc91f539b7248594ca8ad4)
Ticket: https://jira.publiq.be/browse/III-5953
> III-5953 - Styling improvements

- app/index.html
- robots noindex to udb3-angular-app
Ticket: https://jira.publiq.be/browse/III-5943
> III-5943 - Add robots noindex to udb3-angular-app

- app/scripts/controllers/event-detail-ui.js
- Ensure not found offers trigger the promise's rejection
---
Ticket: https://jira.publiq.be/browse/III-5993
> Ensure not found offers trigger the promise's rejection

- app/scripts/app.js
- Ownership page
Ticket: https://jira.uitdatabank.be/browse/III-6356
> III-6356 - Add page ownership

- app/scripts/app.js
- Conditional routing to switch between 'organizers' and 'events-places'
Ticket: https://jira.publiq.be/browse/III-6327
> III-6327-Add conditional routing to switch between 'organizers' and 'events-places'

- app/scripts/app.js
> III-6325- Send the iframe height to the parent

- app/scripts/controllers/newsletter.js
- config.json.dist
- Change newsletter endpoint
Ticket: https://jira.publiq.be/browse/III-6391
Related appconfig PR: https://github.com/cultuurnet/appconfig/pull/889
> III-6391 - Change newsletter endpoint

- app/scripts/services/udbhttpinterceptor.js
- Fixed 403 interceptor not properly ignoring label rejections
---
Requires: https://github.com/cultuurnet/udb3-angular/pull/794
Ticket: https://jira.publiq.be/browse/III-4969
> Fixed 403 interceptor not properly ignoring label rejections
